#if !defined(__CASILLAS__)
#define __CASILLAS__

#include <Arduino.h>
#define NUM_CASILLAS 40

static String nombresCasillas[NUM_CASILLAS] = {
    "SALIDA",
    "SANTA ELENA",
    "ARCA COMUNAL",
    "MACHALA",
    "IMP. RENTA",
    "AERP CUENCA",
    "STO DOMINGO",
    "CASUALIDAD",
    "PORTOVIEJO",
    "MANTA",
    "VISITA CARCEL",
    "PLAZA INDEPEND",
    "EMP ELECTRICA",
    "PARQUE CAROLINA",
    "PAL CARONDELET",
    "AERP QUITO",
    "PANECILLO",
    "ARCA COMUNAL",
    "IGLESIA GUAPULO",
    "PARQUE ITCHIMBIA",
    "PARADA LIBRE",
    "PARQUE IGUANAS",
    "CASUALIDAD",
    "PARQ HISTORICO",
    "MALECON 2000",
    "AERP GUAYAQUIL",
    "LAS PEN^AS",
    "MUNCP GUAYAQUIL",
    "AGUA POTABLE",
    "PARQ CENTENARIO",
    "VAYA A LA CARCEL",
    "CUENCA",
    "RUINAS INGAPIRCA",
    "ARCA COMUNAL",
    "EL CHIMBORAZO",
    "AERP MANTA",
    "CASUALIDAD",
    "ISL GALAPAGOS",
    "IMPUESTOS LUJO",
    "MITAD DEL MUNDO",
};

static short preciosCasillas[NUM_CASILLAS]{
    0,
    60,
    0,
    60,
    -200,
    200,
    100,
    0,
    100,
    120,
    0,
    140,
    150,
    140,
    160,
    200,
    180,
    0,
    180,
    200,
    0,
    220,
    0,
    220,
    240,
    200,
    260,
    260,
    150,
    280,
    0,
    300,
    300,
    0,
    320,
    200,
    0,
    350,
    -75,
    400,
};

#endif // __CASILLAS__
